# Generated by Django 4.2.4 on 2023-08-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Coding', max_length=255),
        ),
    ]
