# Generated by Django 4.2.5 on 2023-10-13 17:33

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_post_likes_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
